Checking environment transitioning

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,6 +4,10 @@ nodeimg: &nodeimg
   docker:
     - image: circleci/node:13.8.0
 
+awscli: &awscli
+  docker:
+    - image: amazon/aws-cli
+
 jobs:
   build-frontend:
     docker:
@@ -91,6 +95,43 @@ jobs:
             cd backend
             npm audit fix --audit-level=critical --force
 
+  deploy-infrastructure:
+    <<: *awscli
+    steps:
+      - checkout
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            echo ${CIRCLE_WORKFLOW_ID:0:7}" workflowid1
+            echo ${CIRCLE_WORKFLOW_ID}" workflowid2
+            export ProjectName=udapeople
+            # aws cloudformation deploy \
+            #   --template-file .circleci/files/backend.yml \
+            #   --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            #   --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+            #   --tags project=udapeople \
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            echo $ProjectName 
+            # aws cloudformation deploy \
+            #   --template-file .circleci/files/frontend.yml \
+            #   --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
+            #   --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+            #   --tags project=your-tag \
+
+      # - run:
+      #     name: Add back-end ip to ansible inventory
+      #     command: |
+      #       export STACK_NAME_BE=back-end-stack-${CIRCLE_WORKFLOW_ID}
+      #       exit 1
+      # - persist_to_workspace:
+      #     root: ~/
+      #     paths:
+      #       - project/.circleci/ansible/inventory.txt
+      # # Here's where you will add some code to rollback on failure
+
+
 workflows:
   default:
     jobs:
@@ -104,3 +145,8 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [develop]
